In [1]:
import numpy as np

**2.Создаем массвы с помощью обычных списков и с использользованием функий NumPy**

In [ ]:
massive1 = np.array([1,2,3,4])
print(massive1) #одномерный массив

[1 2 3 4]


In [28]:
massive2 = np.array([[1,2,3],[3,4,6]])
print(massive2) #двумернный массив
massive2floati = np.array([[1.2,2.3,3.9],[3.123213,4.1232138103812,6.23193821031]])
print(massive2floati) #двумернный массив с флоутами

[[1 2 3]
 [3 4 6]]
[[1.2        2.3        3.9       ]
 [3.123213   4.12321381 6.23193821]]


*Используем функции NumPy*

In [15]:
massive3 = np.arange(1,10,2)
print(massive3)

[1 3 5 7 9]


In [16]:
massive4 = np.arange(10)
print(massive4)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
massive5 = np.zeros((2,3))
print(massive5)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
massive6 = np.ones((2,3))
print(massive6)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
massive7 = np.eye(3)
print(massive7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**3.Вывод формы (shape) и типа данных (dtype) для одного из массивов**

In [ ]:
print("Форма:",massive2.shape) #cмотрим тип данных
print("Тип данных:",massive2.dtype)

Форма: (2, 3)
Тип данных: int64


In [ ]:
print("Форма:",massive2floati.shape)
print("Тип данных:",massive2floati.dtype) #cмотрим форму

Форма: (2, 3)
Тип данных: float64


**4.Примеры индексирования и срезов**

In [ ]:
element = massive2floati[1,2]
print("Отдельный эллемент:", element) #получаем отдельный элемент

Отдельный эллемент: 6.23193821031


In [ ]:
podmasive = massive2floati[:1,2:]
print("Подмасив:", podmasive) #получаем подмасив срезом

Подмасив: [[3.9]]


In [ ]:
row = massive2floati[:1, :]
print("Строка:", row) #выводим строку

Строка: [[1.2 2.3 3.9]]


In [39]:
column = massive2floati[: ,1:]
print("Столбик:", column) #выводим столбец

Столбик: [[2.3        3.9       ]
 [4.12321381 6.23193821]]


**5.Примеры векторных операций и базовых статистик**

In [45]:
mtp1= massive2floati * 12
print(mtp1)
sub1= massive2floati + 12
print(sub1)

[[14.4        27.6        46.8       ]
 [37.478556   49.47856572 74.78325852]]
[[13.2        14.3        15.9       ]
 [15.123213   16.12321381 18.23193821]]


In [43]:
mtp2= massive1 * massive1
print(mtp2)

[ 1  4  9 16]


In [ ]:
sub2 = massive2floati + massive2floati
print(sub2) 

[[ 2.4         4.6         7.8       ]
 [ 6.246426    8.24642762 12.46387642]]


In [51]:
Minik = np.min(sub2)
Maxik = np.max(sub2)
Srednik = np.mean(sub2)

print("Минимально значение масива:",Minik)
print("Максимальное значение масива:",Maxik)
print("Среднее значение масива:",Srednik)

Минимально значение масива: 2.4
Максимальное значение масива: 12.46387642062
Среднее значение масива: 6.959455006897066
